<?php

declare(strict_types=1);
/**
 * Copyright 2019-2022 Seata.io Group.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
namespace Hyperf\Seata\SqlParser\Antlr\MySql\Listener;

use Hyperf\Seata\SqlParser\Antlr\MySql\Parser\Context;
use Hyperf\Seata\SqlParser\Antlr\MySql\Visit\StatementSqlVisitor;
use Hyperf\Seata\SqlParser\Antlr\MySqlContext;

class UpdateSpecificationSqlListener extends MySqlParserBaseListener
{
    private MySqlContext $sqlQueryContext;

    public function __construct(MySqlContext $sqlQueryContext)
    {
        $this->sqlQueryContext = $sqlQueryContext;
    }

    public function enterTableName(Context\TableNameContext $context): void
    {
        parent::enterTableName($context); // TODO: Change the autogenerated stub
    }

    public function enterSingleUpdateStatement(Context\SingleUpdateStatementContext $context): void
    {
        $expressionForUpdateContext = $context->updatedElement()->expression();

        $statementSqlVisitor = new StatementSqlVisitor();

        $text = (string) $statementSqlVisitor->visit($expressionForUpdateContext);
        $this->sqlQueryContext->setWhereCondition($text);

        $uid = $context->uid();

        if ($uid != null) {
            $alias = $uid->getText();
            if (! empty($text)) {
                $this->sqlQueryContext->setTableAlias($alias);
            }
        }
        parent::enterSingleUpdateStatement($context); // TODO: Change the autogenerated stub
    }

    public function enterUpdatedElement(Context\UpdatedElementContext $context): void
    {
        $expression = $context->expression();

        $this->sqlQueryContext->addUpdateValues($expression->getText());

        $fullColumnNameContext = $context->fullColumnName();

        $this->sqlQueryContext->addUpdateColumnNames($fullColumnNameContext->getText());

        parent::enterUpdatedElement($context);
    }
}
