<?php


namespace Hyperf\Seata\Common;


class DefaultValues
{
    const DEFAULT_CLIENT_LOCK_RETRY_INTERVAL = 10;
    const DEFAULT_TM_DEGRADE_CHECK_ALLOW_TIMES = 10;
    const DEFAULT_CLIENT_LOCK_RETRY_TIMES = 30;
    const DEFAULT_CLIENT_LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT = true;
    const DEFAULT_LOG_EXCEPTION_RATE = 100;
    const DEFAULT_CLIENT_ASYNC_COMMIT_BUFFER_LIMIT = 10000;
    const DEFAULT_TM_DEGRADE_CHECK_PERIOD = 2000;
    const DEFAULT_CLIENT_REPORT_RETRY_COUNT = 5;
    const DEFAULT_CLIENT_REPORT_SUCCESS_ENABLE = false;
    const DEFAULT_CLIENT_TABLE_META_CHECK_ENABLE = false;
    const DEFAULT_TABLE_META_CHECKER_INTERVAL = 60000;
    const DEFAULT_TM_DEGRADE_CHECK = false;
    const DEFAULT_CLIENT_SAGA_BRANCH_REGISTER_ENABLE = false;
    const DEFAULT_CLIENT_SAGA_RETRY_PERSIST_MODE_UPDATE = false;
    const DEFAULT_CLIENT_SAGA_COMPENSATE_PERSIST_MODE_UPDATE = false;

    /**
     * Shutdown timeout default 3s
     */
    const DEFAULT_SHUTDOWN_TIMEOUT_SEC = 3;
    const DEFAULT_SELECTOR_THREAD_SIZE = 1;
    const DEFAULT_BOSS_THREAD_SIZE = 1;


    const DEFAULT_SELECTOR_THREAD_PREFIX = "NettyClientSelector";
    const DEFAULT_WORKER_THREAD_PREFIX = "NettyClientWorkerThread";
    const DEFAULT_ENABLE_CLIENT_BATCH_SEND_REQUEST = true;


    const DEFAULT_BOSS_THREAD_PREFIX = "NettyBoss";
    const DEFAULT_NIO_WORKER_THREAD_PREFIX = "NettyServerNIOWorker";
    const DEFAULT_EXECUTOR_THREAD_PREFIX = "NettyServerBizHandler";

    const DEFAULT_TRANSPORT_HEARTBEAT = true;
    const DEFAULT_TRANSACTION_UNDO_DATA_VALIDATION = true;
    const DEFAULT_TRANSACTION_UNDO_LOG_SERIALIZATION = "jackson";
    const DEFAULT_ONLY_CARE_UPDATE_COLUMNS = true;
    /**
     * The constant  DEFAULT_TRANSACTION_UNDO_LOG_TABLE.
     */
    const DEFAULT_TRANSACTION_UNDO_LOG_TABLE = "undo_log";
    /**
     * The constant DEFAULT_STORE_DB_GLOBAL_TABLE.
     */
    const DEFAULT_STORE_DB_GLOBAL_TABLE = "global_table";

    /**
     * The constant DEFAULT_STORE_DB_BRANCH_TABLE.
     */
    const DEFAULT_STORE_DB_BRANCH_TABLE = "branch_table";

    /**
     * The constant DEFAULT_LOCK_DB_TABLE.
     */
    const DEFAULT_LOCK_DB_TABLE = "lock_table";

    const DEFAULT_TM_COMMIT_RETRY_COUNT = 5;
    const DEFAULT_TM_ROLLBACK_RETRY_COUNT = 5;
    const DEFAULT_GLOBAL_TRANSACTION_TIMEOUT = 60000;

    const DEFAULT_TX_GROUP = "my_test_tx_group";
    const DEFAULT_TC_CLUSTER = "default";
    const DEFAULT_GROUPLIST = "127.0.0.1:8091";

    const DEFAULT_DATA_SOURCE_PROXY_MODE = "AT";

    const DEFAULT_DISABLE_GLOBAL_TRANSACTION = false;

    const SERVER_DEFAULT_PORT = 8091;
    const SERVER_DEFAULT_STORE_MODE = "file";

    const DEFAULT_SAGA_JSON_PARSER = "fastjson";

    const DEFAULT_SERVER_ENABLE_CHECK_AUTH = true;

    const DEFAULT_LOAD_BALANCE = "RandomLoadBalance";
    const VIRTUAL_NODES_DEFAULT = 10;

    /**
     * the constant DEFAULT_CLIENT_UNDO_COMPRESS_ENABLE
     */
    const DEFAULT_CLIENT_UNDO_COMPRESS_ENABLE = true;

    /**
     * the constant DEFAULT_CLIENT_UNDO_COMPRESS_TYPE
     */
    const DEFAULT_CLIENT_UNDO_COMPRESS_TYPE = "zip";

    /**
     * the constant DEFAULT_CLIENT_UNDO_COMPRESS_THRESHOLD
     */
    const DEFAULT_CLIENT_UNDO_COMPRESS_THRESHOLD = "64k";

    /**
     * the constant DEFAULT_RETRY_DEAD_THRESHOLD
     */
    const DEFAULT_RETRY_DEAD_THRESHOLD = 2 * 60 * 1000 + 10 * 1000;

    /**
     * the constant TM_INTERCEPTOR_ORDER
     */
    const TM_INTERCEPTOR_ORDER = PHP_INT_MIN + 1000;

    /**
     * the constant TCC_ACTION_INTERCEPTOR_ORDER
     */
    const TCC_ACTION_INTERCEPTOR_ORDER = PHP_INT_MIN + 1000;
}